[package]
name = "whatismyip"
version = "0.1.0"
edition = "2024"

[dependencies]
worker = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
subtle = "2"

[lib]
crate-type = ["cdylib"]
